### ISSUE TITLE
static __init__() missing?

### ISSUE THREAD

**Issue by kevinresol** [benmerckx/genes#13]
This [line of code](https://github.com/kLabz/haxe-react/blob/f0895f43209fecfed86eae21d68e1904f192be7e/src/lib/react/ReactComponent.hx#L123) doesn't seem to appear anywhere in the generate js files. But even if it does I doubt it would work at all.

The magic value is later used in some react render functions:

```haxe
function render() return {"$$typeof": $$tre, ...};
```

cc @klabz

**Comment by benmerckx** [comment]
I'm completely unsure where we could place extern `__init__` code and have it be effective. How is that handled in hxgenjs?

**Comment by benmerckx** [comment]
In this specific case you probably just want to define `react_no_inline`

**Comment by kLabz** [comment]
Yeah it's used for jsx inlining.. though do you even use `jsx()`?

**Comment by kevinresol** [comment]
> How is that handled in hxgenjs?

I can't recall. Perhaps I just used `react_no_inline`



> though do you even use `jsx()`?

Generally no, yeah. Just happen I am experimenting with something...

**Comment by kevinresol** [comment]
How bad is the impact if the value is moved to a static variable, say `ReactType.__tre`?

**Comment by kLabz** [comment]
No idea, what do you think @elsassph?

**Comment by elsassph** [comment]
Hey there :)

In the case of React, we generate "global code", where `$$tre` will be used in every render function. 

In Haxe Modular the approach I used was do actually duplicate any top level `$*` variable in the bundles (not even checking whether they are used). But that's kind of a self-serving hack.

Could it be attached to a class? Yes that could be a cleaner option. It should be hidden from completion though so maybe it could be created purely in macro.

**Comment by kevinresol** [comment]
> It should be hidden from completion

`@:noCompletion` should do the job.

**Comment by kevinresol** [comment]
as for genes on this problem, maybe it should emit a warning for `__init__` on extern class

**Comment by benmerckx** [comment]
Closed this with a warning here. Someday it might make sense to be able to configure for each extern if you want extern `__init__` code either appear before `main()` or in every file the extern is used.
