### ISSUE TITLE
Bypass getter inside getter

### ISSUE THREAD

**Issue by kevinresol** [benmerckx/genes#19]
```haxe
class Main {
	static var inst(get, null):String;
	
	public static function main() {
		trace(inst);
	}
	
	static function get_inst() {
		if(inst == null) inst = 'foo';
		return inst;
	}
}
```

genes generated:
```js
static get inst() {
	return this.get_inst()
}
static get_inst() {
	if (Main.inst == null) {
		Main.inst = "foo";
	};
	return Main.inst;
}
```

which overflows because of the mutual recursion

**Comment by kevinresol** [comment]
Perhaps genes should generate a real underlying variable, e.g.:

```js
Main.__genes__inst;

static get inst() {
	return this.get_inst()
}
static get_inst() {
	if (Main.__genes__inst == null) {
		Main.__genes__inst = "foo";
	};
	return Main.__genes__inst;
}
```

**Comment by benmerckx** [comment]
Oh, that's interesting. I thought this case was only possible with @:isVar, where the native getter would not be generated. Maybe it's different for static properties, I'll have a look.

**Comment by kevinresol** [comment]
iirc `@:isVar` is only useful for `(get/never, set/never)` 
because `null` accessor means the var can be accessed within the class, so there would be a physical var.

**Comment by benmerckx** [comment]
I only generate the native setters/getters for improved interop with js. But as far as generation of code goes I'd like to stay close to what haxe does as maybe some day I can rip out the ExprEmitter for JSGenApi expr/value (which for me depends on haxefoundation/haxe#8625)
