### ISSUE TITLE
tool for merge in one file js and one .d.ts

### ISSUE THREAD

**Issue by francescoagati** [benmerckx/genes#28]
hi,
this library is really good for developement it support also enum. but i have a problem when i must generate one javascript file for deploy a lib with one .d.ts file. i could use hxtsdgen but not support enum export in js. there is a tool that make a merge also of the file .d.ts?

**Comment by benmerckx** [comment]
All I found so far is this: https://github.com/Swatinem/rollup-plugin-dts

It might also be interesting to port the enum types generation back to hxtsdgen: https://github.com/elsassph/hxtsdgen/issues/32#issuecomment-549037318

**Comment by francescoagati** [comment]
Hi @benmerckx ,
is complex modify genes for generate only one file .dts without the split of the javascript files (like in the normal haxe mode for javascript target)
