### ISSUE TITLE
$global is not defined

### ISSUE THREAD

**Issue by benmerckx** [benmerckx/genes#29]
Should transform

https://github.com/HaxeFoundation/haxe/blob/20fe8fb2dcbf7a49d1993404e53bd7ad19842e5b/std/js/Lib.hx#L123

**Comment by kevinresol** [comment]
Just hit this one too

**Comment by benmerckx** [comment]
Can look at it next week. In case it's pressing you can define $global somewhere or check for it here and emit the equivalent of what Haxe defines it as: https://github.com/benmerckx/genes/blob/master/src/genes/es/ExprEmitter.hx#L205
