### ISSUE TITLE
Symbol definition missing in genes generated js code causing Uncaught ReferenceError

### ISSUE THREAD

**Issue by cambiata** [benmerckx/genes#32]
When trying out genes together with haxe-react, I notice a that a symbol that is defined in the standard generated js output...

```haxe
// index.js - standard haxe generated
. . .
var react_ReactMacro = function() { };

// the following line is part of the standard haxe js output:
var $$tre = (typeof Symbol === "function" && Symbol.for && Symbol.for("react.element")) || 0xeac7;  // <------

App.main();
})({});
```

...is missing in the genes generated output, causing a runtime "Uncaught ReferenceError: $$tre is not defined" error.

If I add this missing definition in the genes generated output like the following...
```haxe
// index.js - genes generated
import { Register } from "./genes/Register.js"
import { App } from "./App.js"

// Manually adding the following line to genes generated js output solves the problem:
window.$$tre = (typeof Symbol === "function" && Symbol.for && Symbol.for("react.element")) || 0xeac7;

App.main()

```
...everything works fine.

So, it seems that the genes generator misses this `$$tre` definition - or at least never includes it in the generated code.

Any ideas how to solve this?

/ Jonas

**Comment by benmerckx** [comment]
There's some previous discussion here: https://github.com/benmerckx/genes/issues/13

Basically there's no right way to handle __init__ when files are split that I know of. For this specific issue you can declare it yourself or use `-D reaxt_no_inline`

**Comment by benmerckx** [comment]
See also: https://github.com/kLabz/haxe-react/issues/39

**Comment by cambiata** [comment]
Ah, didn't know of `-D react_no_inline` - it seems to work fine in my case.
Thanks!
