### ISSUE TITLE
request: custom generator

### ISSUE THREAD

**Issue by francescoagati** [benmerckx/genes#62]
for some reasons connected with relative file paths I would need to be able to generate all the js and ts files in one folder instead of having the files separated by folders reflecting the namespace

for example for the class A.hx in the namespace x.y.z
instead of have this folder structure
- main
-   x
-     y
-       z
-          A.js
-          A.ts

i would like to have this folder structure
- main
-     x_y_z_A.js
-     x_y_z_a.ts

can be possible do it this with a custom generator without fork the project for insert custom code?

**Comment by benmerckx** [comment]
There's no setting or anything available. It's hard to see the use case too. Do you have an example setup where this would be required? Maybe a better example project is needed here to help you get going...

**Comment by francescoagati** [comment]
> There's no setting or anything available. It's hard to see the use case too. Do you have an example setup where this would be required? Maybe a better example project is needed here to help you get going...

the big problem is that i use genes with dts2hx and genes dont handle correctly the relative paths generated from dt2hx
for example if i have a file in folder ./a/b/c/x.tsx dts2hx create a file definition with this path but genes dont handle paths from root
