### ISSUE TITLE
Merge "field access" imports

### ISSUE THREAD

**Issue by kevinresol** [benmerckx/genes#7]
Something like this
```haxe
@:jsRequire('semantic-ui-react', 'Dropdown.Header')
```

produces:
```js
import {Dropdown.Header, Dropdown.Menu, Dropdown} from "semantic-ui-react"
```

and that causes syntax error.

In fact a single `import {Dropdown} from ...` suffices.

**Comment by kevinresol** [comment]
Now it generates `import Dropdown from "semantic-ui-react"`, missing curly braces?

**Comment by kevinresol** [comment]
I got my 1.7MB js (bundled 6MB) web app running after manually patching for this one. And _apparently_ everything is working!

**Comment by benmerckx** [comment]
Magical! :) I imagine you're going this route to eventually get tree shaking going? I still have to look  into the requirements to mark haxe classes as "shakeable".

**Comment by kevinresol** [comment]
Yeah tree shaking and split bundle :)
Thanks for the amazing work and prompt responses!
